#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ "$1" = purge ]; then
            rm -rf /etc/savvy-go /var/lib/savvy-go
        fi
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
        fi
        ;;
esac

exit 0
