// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/shopspring/decimal"
)

const accountDailyDeltas = `-- name: AccountDailyDeltas :many
WITH p AS (SELECT CAST(?2 AS INTEGER) AS id)
SELECT t.date AS day,
	CAST(SUM(
		CASE WHEN t.account_id = p.id THEN
			CASE WHEN t.type IN ('income', 'debt_collection', 'debt_borrow') THEN t.amount ELSE -t.amount END
		ELSE 0 END
		+ CASE WHEN t.to_account_id = p.id AND t.type = 'transfer' THEN COALESCE(t.to_amount, 0) ELSE 0 END
	) AS INTEGER) AS delta
FROM transactions t, p
WHERE t.status = 'confirmed' AND (t.account_id = p.id OR t.to_account_id = p.id)
	AND t.date <= COALESCE(?1, t.date)
GROUP BY t.date
ORDER BY t.date
`

type AccountDailyDeltasParams struct {
	AsOf sql.NullString
	ID   int64
}

type AccountDailyDeltasRow struct {
	Day   sql.NullString
	Delta int64
}

// The net change of a non-debt account per day, oldest first, for confirmed
// transactions up to as_of (all of them when NULL). This is the only place that
// knows how a transaction moves money: it adds to the account for income,
// debt_collection and debt_borrow, takes from it for every other type, and a
// transfer adds to_amount to its destination account (a transfer from an account
// to itself therefore does both). A balance is the sum of these rows, a balance
// history their running total.
// CAST: sqlc would type a SUM as float; the sum of integers is an integer.
func (q *Queries) AccountDailyDeltas(ctx context.Context, arg AccountDailyDeltasParams) ([]AccountDailyDeltasRow, error) {
	rows, err := q.db.QueryContext(ctx, accountDailyDeltas, arg.AsOf, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountDailyDeltasRow{}
	for rows.Next() {
		var i AccountDailyDeltasRow
		if err := rows.Scan(&i.Day, &i.Delta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT COUNT(*) FROM transactions WHERE account_id = ? OR to_account_id = ?
`

type CountAccountTransactionsParams struct {
	AccountID   int64
	ToAccountID sql.NullInt64
}

func (q *Queries) CountAccountTransactions(ctx context.Context, arg CountAccountTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountTransactions, arg.AccountID, arg.ToAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDebtHistory = `-- name: CountDebtHistory :one
SELECT COUNT(*) FROM transactions
WHERE to_account_id = ? AND type IN ('debt_payment','debt_collection')
`

func (q *Queries) CountDebtHistory(ctx context.Context, toAccountID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDebtHistory, toAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteDebtAccount = `-- name: DeleteDebtAccount :exec
DELETE FROM accounts WHERE id = ? AND type = 'debt'
`

func (q *Queries) DeleteDebtAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDebtAccount, id)
	return err
}

const deleteDebtIssuance = `-- name: DeleteDebtIssuance :exec
DELETE FROM transactions WHERE to_account_id = ? AND type IN ('debt_lend','debt_borrow')
`

func (q *Queries) DeleteDebtIssuance(ctx context.Context, toAccountID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteDebtIssuance, toAccountID)
	return err
}

const getAccountUnit = `-- name: GetAccountUnit :one
SELECT c.id, c.decimals FROM accounts a JOIN currencies c ON c.id = a.currency_id WHERE a.id = ?
`

type GetAccountUnitRow struct {
	ID       int64
	Decimals int64
}

func (q *Queries) GetAccountUnit(ctx context.Context, id int64) (GetAccountUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountUnit, id)
	var i GetAccountUnitRow
	err := row.Scan(&i.ID, &i.Decimals)
	return i, err
}

const insertAccount = `-- name: InsertAccount :execresult
INSERT INTO accounts (name, type, debt_type, currency_id, initial_balance, target_amount, due_date,
	is_paid_off, counterparty, debt_description, is_active, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccountParams struct {
	Name            string
	Type            string
	DebtType        sql.NullString
	CurrencyID      int64
	InitialBalance  int64
	TargetAmount    sql.NullInt64
	DueDate         sql.NullString
	IsPaidOff       int64
	Counterparty    sql.NullString
	DebtDescription sql.NullString
	IsActive        int64
	SortOrder       int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAccount,
		arg.Name,
		arg.Type,
		arg.DebtType,
		arg.CurrencyID,
		arg.InitialBalance,
		arg.TargetAmount,
		arg.DueDate,
		arg.IsPaidOff,
		arg.Counterparty,
		arg.DebtDescription,
		arg.IsActive,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.name, a.type, a.currency_id, a.initial_balance, a.is_active, a.sort_order,
	a.debt_type, a.target_amount, a.due_date, a.is_paid_off, a.counterparty, a.debt_description, a.created_at,
	c.id AS currency_id_join, c.code, c.name AS currency_name, c.symbol, c.decimals, c.is_base, c.rate
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
WHERE a.id = COALESCE(?1, a.id)
  AND a.is_active = COALESCE(?2, a.is_active)
  AND CASE a.type WHEN 'bank' THEN 1 WHEN 'crypto' THEN 1 WHEN 'cash' THEN 1 ELSE 0 END
      >= COALESCE(CAST(?3 AS INTEGER), 0)
  AND CASE a.type WHEN 'debt' THEN 1 ELSE 0 END >= COALESCE(CAST(?4 AS INTEGER), 0)
  AND a.is_paid_off <= CASE WHEN CAST(?5 AS INTEGER) IS NULL THEN 1 ELSE 0 END
ORDER BY CASE WHEN a.type = 'debt' THEN 1 ELSE 0 END, a.sort_order, a.id
`

type ListAccountsParams struct {
	ID           sql.NullInt64
	OnlyActive   sql.NullInt64
	ExcludeDebts sql.NullInt64
	OnlyDebts    sql.NullInt64
	UnpaidOnly   sql.NullInt64
}

type ListAccountsRow struct {
	ID              int64
	Name            string
	Type            string
	CurrencyID      int64
	InitialBalance  int64
	IsActive        int64
	SortOrder       int64
	DebtType        sql.NullString
	TargetAmount    sql.NullInt64
	DueDate         sql.NullString
	IsPaidOff       int64
	Counterparty    sql.NullString
	DebtDescription sql.NullString
	CreatedAt       sql.NullString
	CurrencyIDJoin  int64
	Code            string
	CurrencyName    string
	Symbol          string
	Decimals        int64
	IsBase          int64
	Rate            decimal.Decimal
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts,
		arg.ID,
		arg.OnlyActive,
		arg.ExcludeDebts,
		arg.OnlyDebts,
		arg.UnpaidOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CurrencyID,
			&i.InitialBalance,
			&i.IsActive,
			&i.SortOrder,
			&i.DebtType,
			&i.TargetAmount,
			&i.DueDate,
			&i.IsPaidOff,
			&i.Counterparty,
			&i.DebtDescription,
			&i.CreatedAt,
			&i.CurrencyIDJoin,
			&i.Code,
			&i.CurrencyName,
			&i.Symbol,
			&i.Decimals,
			&i.IsBase,
			&i.Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountPaidOff = `-- name: MarkAccountPaidOff :exec
UPDATE accounts SET is_paid_off = 1 WHERE id = ?
`

func (q *Queries) MarkAccountPaidOff(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAccountPaidOff, id)
	return err
}

const nextAccountSortOrder = `-- name: NextAccountSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM accounts
WHERE CASE WHEN ?1 IS NULL THEN type IN ('bank','crypto','cash') ELSE type = 'debt' END
`

func (q *Queries) NextAccountSortOrder(ctx context.Context, debtOnly interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAccountSortOrder, debtOnly)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reopenAccount = `-- name: ReopenAccount :exec
UPDATE accounts SET is_paid_off = 0, updated_at = ? WHERE id = ?
`

type ReopenAccountParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) ReopenAccount(ctx context.Context, arg ReopenAccountParams) error {
	_, err := q.db.ExecContext(ctx, reopenAccount, arg.UpdatedAt, arg.ID)
	return err
}

const setAccountSortOrder = `-- name: SetAccountSortOrder :exec
UPDATE accounts SET sort_order = ? WHERE id = ?
`

type SetAccountSortOrderParams struct {
	SortOrder int64
	ID        int64
}

func (q *Queries) SetAccountSortOrder(ctx context.Context, arg SetAccountSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setAccountSortOrder, arg.SortOrder, arg.ID)
	return err
}

const sumDebtPayments = `-- name: SumDebtPayments :one
SELECT CAST(COALESCE(SUM(to_amount),0) AS INTEGER) FROM transactions
WHERE to_account_id = ? AND status = 'confirmed' AND type IN ('debt_payment','debt_collection')
`

func (q *Queries) SumDebtPayments(ctx context.Context, toAccountID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumDebtPayments, toAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET name=?, type=?, currency_id=?, initial_balance=?, is_active=?,
	debt_type=?, target_amount=?, due_date=?, is_paid_off=?, counterparty=?, debt_description=?, updated_at=?
WHERE id=?
`

type UpdateAccountParams struct {
	Name            string
	Type            string
	CurrencyID      int64
	InitialBalance  int64
	IsActive        int64
	DebtType        sql.NullString
	TargetAmount    sql.NullInt64
	DueDate         sql.NullString
	IsPaidOff       int64
	Counterparty    sql.NullString
	DebtDescription sql.NullString
	UpdatedAt       sql.NullString
	ID              int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.CurrencyID,
		arg.InitialBalance,
		arg.IsActive,
		arg.DebtType,
		arg.TargetAmount,
		arg.DueDate,
		arg.IsPaidOff,
		arg.Counterparty,
		arg.DebtDescription,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
