// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAPIToken = `-- name: DeleteAPIToken :execresult
DELETE FROM api_tokens WHERE id = ? AND user_id = ?
`

type DeleteAPITokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, prefix, scope, expires_at, last_used_at, created_at, updated_at
FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :execresult
INSERT INTO api_tokens (user_id, name, token_hash, prefix, scope, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAPITokenParams struct {
	UserID    int64
	Name      string
	TokenHash string
	Prefix    string
	Scope     string
	ExpiresAt sql.NullString
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.Scope,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, token_hash, prefix, scope, expires_at, last_used_at, created_at, updated_at
FROM api_tokens WHERE user_id = ? ORDER BY id DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scope,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAPITokenParams struct {
	LastUsedAt sql.NullString
	ID         int64
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
