// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const categoryStatistics = `-- name: CategoryStatistics :one
SELECT COUNT(*), COALESCE(SUM(amount),0) FROM transactions
WHERE category_id = ?1 AND status = 'confirmed'
  AND date >= COALESCE(?2, date)
  AND date <= COALESCE(?3, date)
`

type CategoryStatisticsParams struct {
	CategoryID sql.NullInt64
	StartDate  sql.NullString
	EndDate    sql.NullString
}

type CategoryStatisticsRow struct {
	Count    int64
	Coalesce interface{}
}

func (q *Queries) CategoryStatistics(ctx context.Context, arg CategoryStatisticsParams) (CategoryStatisticsRow, error) {
	row := q.db.QueryRowContext(ctx, categoryStatistics, arg.CategoryID, arg.StartDate, arg.EndDate)
	var i CategoryStatisticsRow
	err := row.Scan(&i.Count, &i.Coalesce)
	return i, err
}

const clearDefaultCategory = `-- name: ClearDefaultCategory :exec
UPDATE categories SET is_default = 0 WHERE type = ? AND is_default = 1
`

func (q *Queries) ClearDefaultCategory(ctx context.Context, type_ string) error {
	_, err := q.db.ExecContext(ctx, clearDefaultCategory, type_)
	return err
}

const countCategoriesByType = `-- name: CountCategoriesByType :one
SELECT COUNT(*) FROM categories WHERE type = ?
`

func (q *Queries) CountCategoriesByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT categories.id, categories.name, categories.type, categories.icon, categories.color, categories.is_default,
	(SELECT COUNT(*) FROM transactions t WHERE t.category_id = categories.id)
FROM categories WHERE categories.id = ?
`

type GetCategoryRow struct {
	ID        int64
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	Count     int64
}

func (q *Queries) GetCategory(ctx context.Context, id int64) (GetCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.IsDefault,
		&i.Count,
	)
	return i, err
}

const getDefaultCategory = `-- name: GetDefaultCategory :one
SELECT categories.id, categories.name, categories.type, categories.icon, categories.color, categories.is_default,
	(SELECT COUNT(*) FROM transactions t WHERE t.category_id = categories.id)
FROM categories WHERE categories.type = ? AND categories.is_default = 1 LIMIT 1
`

type GetDefaultCategoryRow struct {
	ID        int64
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	Count     int64
}

func (q *Queries) GetDefaultCategory(ctx context.Context, type_ string) (GetDefaultCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCategory, type_)
	var i GetDefaultCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.IsDefault,
		&i.Count,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :execresult
INSERT INTO categories (name, type, icon, color, is_default, created_at, updated_at) VALUES (?,?,?,?,?,?,?)
`

type InsertCategoryParams struct {
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCategory,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.name, c.type, c.icon, c.color, c.is_default,
	(SELECT COUNT(*) FROM transactions t WHERE t.category_id = c.id)
FROM categories c
WHERE c.type = COALESCE(?1, c.type)
ORDER BY c.name
`

type ListCategoriesRow struct {
	ID        int64
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	Count     int64
}

func (q *Queries) ListCategories(ctx context.Context, type_ sql.NullString) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.IsDefault,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCategoryTransactions = `-- name: ReassignCategoryTransactions :exec
UPDATE transactions SET category_id = ? WHERE category_id = ?
`

type ReassignCategoryTransactionsParams struct {
	CategoryID   sql.NullInt64
	CategoryID_2 sql.NullInt64
}

func (q *Queries) ReassignCategoryTransactions(ctx context.Context, arg ReassignCategoryTransactionsParams) error {
	_, err := q.db.ExecContext(ctx, reassignCategoryTransactions, arg.CategoryID, arg.CategoryID_2)
	return err
}

const setCategoryDefault = `-- name: SetCategoryDefault :exec
UPDATE categories SET is_default = 1, updated_at = ? WHERE id = ?
`

type SetCategoryDefaultParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) SetCategoryDefault(ctx context.Context, arg SetCategoryDefaultParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryDefault, arg.UpdatedAt, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name=?, type=?, icon=?, color=?, is_default=?, updated_at=? WHERE id=?
`

type UpdateCategoryParams struct {
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.IsDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
