// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

type Account struct {
	ID              int64
	Name            string
	Type            string
	DebtType        sql.NullString
	CurrencyID      int64
	InitialBalance  int64
	TargetAmount    sql.NullInt64
	DueDate         sql.NullString
	IsPaidOff       int64
	Counterparty    sql.NullString
	DebtDescription sql.NullString
	IsActive        int64
	SortOrder       int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type AdminAudit struct {
	ID           int64
	ActorID      sql.NullInt64
	Action       string
	SpaceID      sql.NullInt64
	TargetUserID sql.NullInt64
	Details      sql.NullString
	CreatedAt    string
}

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  string
	Prefix     string
	Scope      string
	ExpiresAt  sql.NullString
	LastUsedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type AuthSession struct {
	ID                int64
	UserID            int64
	TokenHash         string
	Csrf              string
	Ip                sql.NullString
	UserAgent         sql.NullString
	RememberMe        int64
	LastUsedAt        string
	RefreshedAt       sql.NullString
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	RevokedAt         sql.NullString
	CreatedAt         sql.NullString
	UpdatedAt         sql.NullString
}

type AutomationRule struct {
	ID             int64
	Name           string
	Description    sql.NullString
	TriggerType    string
	Priority       int64
	Conditions     string
	Actions        string
	IsActive       int64
	StopProcessing int64
	RunsCount      int64
	LastRunAt      sql.NullString
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}

type AutomationRuleLog struct {
	ID                int64
	RuleID            int64
	TriggerEntityType sql.NullString
	TriggerEntityID   sql.NullInt64
	ActionsExecuted   sql.NullString
	Status            string
	ErrorMessage      sql.NullString
	CreatedAt         string
}

type Budget struct {
	ID              int64
	Name            string
	Amount          int64
	CurrencyID      int64
	Period          string
	StartDate       sql.NullString
	EndDate         sql.NullString
	IsGlobal        int64
	NotifyAtPercent sql.NullInt64
	IsActive        int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type BudgetCategory struct {
	BudgetID   int64
	CategoryID int64
}

type BudgetTag struct {
	BudgetID int64
	TagID    int64
}

type Category struct {
	ID        int64
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	IsDefault int64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Currency struct {
	ID        int64
	Code      string
	Name      string
	Symbol    string
	Decimals  int64
	IsBase    int64
	Rate      decimal.Decimal
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type IdentityProvider struct {
	ID              int64
	Name            string
	Slug            string
	Protocol        string
	Preset          string
	Enabled         int64
	SortOrder       int64
	Config          sql.NullString
	Secrets         sql.NullString
	ClaimMappings   sql.NullString
	RoleMapping     sql.NullString
	DefaultRole     string
	AllowJit        int64
	SyncRoleOnLogin int64
	LinkByEmail     int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type PasswordToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type RecurringTransaction struct {
	ID          int64
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      int64
	ToAmount    sql.NullInt64
	IsEstimated int64
	Description sql.NullString
	Frequency   string
	Interval    int64
	DayOfWeek   sql.NullInt64
	DayOfMonth  sql.NullInt64
	StartDate   string
	EndDate     sql.NullString
	NextRunDate string
	LastRunDate sql.NullString
	IsActive    int64
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type RecurringTransactionTag struct {
	RecurringTransactionID int64
	TagID                  int64
}

type SchemaMigration struct {
	Version   string
	AppliedAt string
}

type Setting struct {
	Key   string
	Value sql.NullString
}

type Space struct {
	ID         int64
	Uuid       string
	Name       string
	QuotaBytes sql.NullInt64
	CreatedBy  sql.NullInt64
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type SpaceInvitation struct {
	ID                   int64
	SpaceID              int64
	Email                sql.NullString
	Role                 string
	TokenHash            string
	InvitedBy            sql.NullInt64
	InvitedByServerAdmin int64
	ExpiresAt            string
	AcceptedAt           sql.NullString
	AcceptedBy           sql.NullInt64
	CreatedAt            sql.NullString
}

type SpaceLink struct {
	SpaceAID  int64
	SpaceBID  int64
	CreatedBy sql.NullInt64
	CreatedAt sql.NullString
}

type SpaceMember struct {
	SpaceID   int64
	UserID    int64
	Role      string
	CreatedAt sql.NullString
}

type SpaceSetting struct {
	Key   string
	Value sql.NullString
}

type SpaceTransfer struct {
	Uuid          string
	FromSpaceUuid string
	FromAccountID int64
	FromAmount    int64
	FromCurrency  string
	FromDecimals  int64
	ToSpaceUuid   string
	ToAccountID   int64
	ToAmount      int64
	ToCurrency    string
	ToDecimals    int64
	Date          string
	Description   sql.NullString
	CreatedBy     sql.NullInt64
	Version       int64
	DeletedAt     sql.NullString
	SigV          int64
	SignerKid     sql.NullString
	Signature     sql.NullString
	Status        string
	Review        sql.NullString
	Remote        sql.NullString
	UpdatedAt     sql.NullString
}

type SsoLoginState struct {
	ID                 int64
	State              string
	IdentityProviderID int64
	Nonce              sql.NullString
	CodeVerifier       sql.NullString
	SamlRequestID      sql.NullString
	RedirectAfter      sql.NullString
	ExpiresAt          string
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type SsoLoginTicket struct {
	ID             int64
	Ticket         string
	UserID         int64
	Requires2fa    int64
	TwoFactorToken sql.NullString
	ExpiresAt      string
	ConsumedAt     sql.NullString
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Transaction struct {
	ID                     int64
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 int64
	ToAmount               sql.NullInt64
	IsEstimated            int64
	Description            sql.NullString
	DedupHash              sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	SpaceTransferUuid      sql.NullString
	CreatedBy              sql.NullInt64
	CreatedAt              sql.NullString
	UpdatedAt              sql.NullString
}

type TransactionImport struct {
	ID            string
	UserID        sql.NullInt64
	UploadID      sql.NullString
	Status        string
	Mapping       sql.NullString
	Options       sql.NullString
	TotalRows     sql.NullInt64
	ProcessedRows int64
	CreatedCount  int64
	SkippedCount  int64
	ErrorCount    int64
	Errors        sql.NullString
	Meta          sql.NullString
	Message       sql.NullString
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

type TransactionItem struct {
	ID            int64
	TransactionID int64
	Name          string
	Quantity      decimal.Decimal
	PricePerUnit  int64
	TotalPrice    int64
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}

type TrustedKey struct {
	Kid       string
	PublicKey string
	Name      string
	AddedBy   sql.NullInt64
	CreatedAt sql.NullString
}

type TwoFactorChallenge struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type TwoFactorRecoveryCode struct {
	ID        int64
	UserID    int64
	Code      string
	UsedAt    sql.NullString
	CreatedAt sql.NullString
}

type Upload struct {
	ID           string
	UserID       sql.NullInt64
	Bucket       string
	ObjectKey    string
	Disk         string
	Path         sql.NullString
	OriginalName string
	MimeType     sql.NullString
	Size         sql.NullInt64
	PartSize     sql.NullInt64
	TotalParts   sql.NullInt64
	Status       string
	CompletedAt  sql.NullString
	ExpiresAt    sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}

type User struct {
	ID                 int64
	Name               string
	Email              string
	Password           sql.NullString
	Role               string
	IsSsoOnly          int64
	TwoFactorSecret    sql.NullString
	TwoFactorEnabled   int64
	TwoFactorConfirmed int64
	DeletedAt          sql.NullString
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type UserIdentity struct {
	ID                 int64
	UserID             int64
	IdentityProviderID int64
	Subject            string
	LastLoginAt        sql.NullString
	Claims             sql.NullString
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type WebauthnChallenge struct {
	ID         int64
	UserID     sql.NullInt64
	TokenHash  string
	Type       string
	Options    string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type WebauthnCredential struct {
	ID           int64
	UserID       int64
	CredentialID string
	Name         sql.NullString
	Aaguid       sql.NullString
	Record       string
	Counter      int64
	LastUsedAt   sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}
