// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package sqlc

import (
	"context"
)

const listSchemaMigrations = `-- name: ListSchemaMigrations :many
SELECT version FROM schema_migrations
`

func (q *Queries) ListSchemaMigrations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
