// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: space_settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSpaceSetting = `-- name: GetSpaceSetting :one
SELECT value FROM space_settings WHERE key = ?
`

func (q *Queries) GetSpaceSetting(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSpaceSetting, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const listSpaceSettings = `-- name: ListSpaceSettings :many
SELECT key, value FROM space_settings
`

func (q *Queries) ListSpaceSettings(ctx context.Context) ([]SpaceSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpaceSetting{}
	for rows.Next() {
		var i SpaceSetting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpaceSetting = `-- name: UpsertSpaceSetting :exec
INSERT INTO space_settings(key, value) VALUES(?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSpaceSettingParams struct {
	Key   string
	Value sql.NullString
}

func (q *Queries) UpsertSpaceSetting(ctx context.Context, arg UpsertSpaceSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSpaceSetting, arg.Key, arg.Value)
	return err
}
