// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSpaceRow = `-- name: DeleteSpaceRow :exec
DELETE FROM spaces WHERE id = ?
`

func (q *Queries) DeleteSpaceRow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceRow, id)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM space_members WHERE space_id = ? AND user_id = ?
`

type GetMemberRoleParams struct {
	SpaceID int64
	UserID  int64
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.SpaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSpace = `-- name: GetSpace :one
SELECT id, uuid, name, created_by, created_at, updated_at FROM spaces WHERE id = ?
`

func (q *Queries) GetSpace(ctx context.Context, id int64) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpace, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSpace = `-- name: InsertSpace :one
INSERT INTO spaces (uuid, name, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertSpaceParams struct {
	Uuid      string
	Name      string
	CreatedBy sql.NullInt64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertSpace(ctx context.Context, arg InsertSpaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSpace,
		arg.Uuid,
		arg.Name,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSpaceIDs = `-- name: ListSpaceIDs :many
SELECT id FROM spaces ORDER BY id
`

func (q *Queries) ListSpaceIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSpaces = `-- name: ListUserSpaces :many
SELECT s.id, s.uuid, s.name, m.role
FROM space_members m JOIN spaces s ON s.id = m.space_id
WHERE m.user_id = ?
ORDER BY s.id
`

type ListUserSpacesRow struct {
	ID   int64
	Uuid string
	Name string
	Role string
}

func (q *Queries) ListUserSpaces(ctx context.Context, userID int64) ([]ListUserSpacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSpacesRow{}
	for rows.Next() {
		var i ListUserSpacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spaceIDByUUID = `-- name: SpaceIDByUUID :one
SELECT id FROM spaces WHERE uuid = ?
`

func (q *Queries) SpaceIDByUUID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, spaceIDByUUID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSpaceMember = `-- name: UpsertSpaceMember :exec
INSERT INTO space_members (space_id, user_id, role, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (space_id, user_id) DO UPDATE SET role = excluded.role
`

type UpsertSpaceMemberParams struct {
	SpaceID   int64
	UserID    int64
	Role      string
	CreatedAt sql.NullString
}

func (q *Queries) UpsertSpaceMember(ctx context.Context, arg UpsertSpaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertSpaceMember,
		arg.SpaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}
