// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"

	"github.com/shopspring/decimal"
)

const confirmTransaction = `-- name: ConfirmTransaction :exec
UPDATE transactions SET status='confirmed', amount=?, to_amount=?, is_estimated=0, date=?, updated_at=? WHERE id=?
`

type ConfirmTransactionParams struct {
	Amount    int64
	ToAmount  sql.NullInt64
	Date      sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

// A confirmed transaction has its real amount, so it is no longer an estimate.
func (q *Queries) ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) error {
	_, err := q.db.ExecContext(ctx, confirmTransaction,
		arg.Amount,
		arg.ToAmount,
		arg.Date,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countAllTransactions = `-- name: CountAllTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountAllTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionItems = `-- name: DeleteTransactionItems :exec
DELETE FROM transaction_items WHERE transaction_id = ?
`

func (q *Queries) DeleteTransactionItems(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionItems, transactionID)
	return err
}

const deleteTransactionTags = `-- name: DeleteTransactionTags :exec
DELETE FROM transaction_tag WHERE transaction_id = ?
`

func (q *Queries) DeleteTransactionTags(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionTags, transactionID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.type, t.account_id, t.to_account_id, t.category_id, t.amount, t.to_amount,
	t.is_estimated, t.description, t.date, t.status, t.recurring_transaction_id, t.created_at,
	ca.id AS currency_id, ca.decimals AS decimals,
	COALESCE(cb.id, ca.id) AS to_currency_id, COALESCE(cb.decimals, ca.decimals) AS to_decimals
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN currencies ca ON ca.id = a.currency_id
LEFT JOIN accounts ta ON ta.id = t.to_account_id
LEFT JOIN currencies cb ON cb.id = ta.currency_id
WHERE t.id = ?
`

type GetTransactionRow struct {
	ID                     int64
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 int64
	ToAmount               sql.NullInt64
	IsEstimated            int64
	Description            sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	CreatedAt              sql.NullString
	CurrencyID             int64
	Decimals               int64
	ToCurrencyID           int64
	ToDecimals             int64
}

// Lists go through filter.ListTransactions, which selects the same columns.
func (q *Queries) GetTransaction(ctx context.Context, id int64) (GetTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Amount,
		&i.ToAmount,
		&i.IsEstimated,
		&i.Description,
		&i.Date,
		&i.Status,
		&i.RecurringTransactionID,
		&i.CreatedAt,
		&i.CurrencyID,
		&i.Decimals,
		&i.ToCurrencyID,
		&i.ToDecimals,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :execresult
INSERT INTO transactions (type, account_id, to_account_id, category_id, amount, to_amount, is_estimated,
	description, date, status, recurring_transaction_id, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertTransactionParams struct {
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 int64
	ToAmount               sql.NullInt64
	IsEstimated            int64
	Description            sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	CreatedAt              sql.NullString
	UpdatedAt              sql.NullString
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTransaction,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.IsEstimated,
		arg.Description,
		arg.Date,
		arg.Status,
		arg.RecurringTransactionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertTransactionIgnoreDup = `-- name: InsertTransactionIgnoreDup :execresult
INSERT OR IGNORE INTO transactions (type, account_id, category_id, amount, description, date, status, dedup_hash, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertTransactionIgnoreDupParams struct {
	Type        string
	AccountID   int64
	CategoryID  sql.NullInt64
	Amount      int64
	Description sql.NullString
	Date        sql.NullString
	Status      string
	DedupHash   sql.NullString
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

func (q *Queries) InsertTransactionIgnoreDup(ctx context.Context, arg InsertTransactionIgnoreDupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTransactionIgnoreDup,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Date,
		arg.Status,
		arg.DedupHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertTransactionItem = `-- name: InsertTransactionItem :exec
INSERT INTO transaction_items (transaction_id, name, quantity, price_per_unit, total_price, created_at, updated_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertTransactionItemParams struct {
	TransactionID int64
	Name          string
	Quantity      decimal.Decimal
	PricePerUnit  int64
	TotalPrice    int64
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

func (q *Queries) InsertTransactionItem(ctx context.Context, arg InsertTransactionItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionItem,
		arg.TransactionID,
		arg.Name,
		arg.Quantity,
		arg.PricePerUnit,
		arg.TotalPrice,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTransactionTag = `-- name: InsertTransactionTag :exec
INSERT OR IGNORE INTO transaction_tag (transaction_id, tag_id) VALUES (?,?)
`

type InsertTransactionTagParams struct {
	TransactionID int64
	TagID         int64
}

func (q *Queries) InsertTransactionTag(ctx context.Context, arg InsertTransactionTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const listItemsOfTransactions = `-- name: ListItemsOfTransactions :many
SELECT transaction_id, id, name, quantity, price_per_unit, total_price FROM transaction_items
WHERE transaction_id IN (/*SLICE:ids*/?)
ORDER BY transaction_id, id
`

type ListItemsOfTransactionsRow struct {
	TransactionID int64
	ID            int64
	Name          string
	Quantity      decimal.Decimal
	PricePerUnit  int64
	TotalPrice    int64
}

func (q *Queries) ListItemsOfTransactions(ctx context.Context, ids []int64) ([]ListItemsOfTransactionsRow, error) {
	query := listItemsOfTransactions
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsOfTransactionsRow{}
	for rows.Next() {
		var i ListItemsOfTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.Name,
			&i.Quantity,
			&i.PricePerUnit,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsOfTransactions = `-- name: ListTagsOfTransactions :many
SELECT tt.transaction_id, tags.id, tags.name, tags.created_at FROM tags
JOIN transaction_tag tt ON tt.tag_id = tags.id
WHERE tt.transaction_id IN (/*SLICE:ids*/?)
ORDER BY tt.transaction_id, tags.name
`

type ListTagsOfTransactionsRow struct {
	TransactionID int64
	ID            int64
	Name          string
	CreatedAt     sql.NullString
}

func (q *Queries) ListTagsOfTransactions(ctx context.Context, ids []int64) ([]ListTagsOfTransactionsRow, error) {
	query := listTagsOfTransactions
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsOfTransactionsRow{}
	for rows.Next() {
		var i ListTagsOfTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionSummaryRows = `-- name: ListTransactionSummaryRows :many
SELECT t.type, t.amount, c.rate, c.is_base, c.decimals
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN currencies c ON c.id = a.currency_id
WHERE t.status = ? AND t.type IN ('income','expense')
`

type ListTransactionSummaryRowsRow struct {
	Type     string
	Amount   int64
	Rate     decimal.Decimal
	IsBase   int64
	Decimals int64
}

func (q *Queries) ListTransactionSummaryRows(ctx context.Context, status string) ([]ListTransactionSummaryRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionSummaryRows, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionSummaryRowsRow{}
	for rows.Next() {
		var i ListTransactionSummaryRowsRow
		if err := rows.Scan(
			&i.Type,
			&i.Amount,
			&i.Rate,
			&i.IsBase,
			&i.Decimals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipTransaction = `-- name: SkipTransaction :exec
UPDATE transactions SET status='skipped', updated_at=? WHERE id=?
`

type SkipTransactionParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) SkipTransaction(ctx context.Context, arg SkipTransactionParams) error {
	_, err := q.db.ExecContext(ctx, skipTransaction, arg.UpdatedAt, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET type=?, account_id=?, to_account_id=?, category_id=?, amount=?, to_amount=?,
	is_estimated=?, description=?, date=?, updated_at=? WHERE id=?
`

type UpdateTransactionParams struct {
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      int64
	ToAmount    sql.NullInt64
	IsEstimated int64
	Description sql.NullString
	Date        sql.NullString
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.IsEstimated,
		arg.Description,
		arg.Date,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :exec
UPDATE transactions SET category_id=?, updated_at=? WHERE id=?
`

type UpdateTransactionCategoryParams struct {
	CategoryID sql.NullInt64
	UpdatedAt  sql.NullString
	ID         int64
}

func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionCategory, arg.CategoryID, arg.UpdatedAt, arg.ID)
	return err
}

const updateTransactionDescription = `-- name: UpdateTransactionDescription :exec
UPDATE transactions SET description=?, updated_at=? WHERE id=?
`

type UpdateTransactionDescriptionParams struct {
	Description sql.NullString
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) UpdateTransactionDescription(ctx context.Context, arg UpdateTransactionDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionDescription, arg.Description, arg.UpdatedAt, arg.ID)
	return err
}
