// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = ? AND deleted_at IS NULL
`

func (q *Queries) CountAdmins(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserAPITokens = `-- name: DeleteUserAPITokens :exec
DELETE FROM api_tokens WHERE user_id = ?
`

func (q *Queries) DeleteUserAPITokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserAPITokens, userID)
	return err
}

const deleteUserCredentials = `-- name: DeleteUserCredentials :exec
DELETE FROM auth_sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserCredentials(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserCredentials, userID)
	return err
}

const deleteUserIdentities = `-- name: DeleteUserIdentities :exec
DELETE FROM user_identities WHERE user_id = ?
`

func (q *Queries) DeleteUserIdentities(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserIdentities, userID)
	return err
}

const deleteUserPasskeys = `-- name: DeleteUserPasskeys :exec
DELETE FROM webauthn_credentials WHERE user_id = ?
`

func (q *Queries) DeleteUserPasskeys(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPasskeys, userID)
	return err
}

const deleteUserPasswordTokens = `-- name: DeleteUserPasswordTokens :exec
DELETE FROM password_tokens WHERE user_id = ?
`

func (q *Queries) DeleteUserPasswordTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPasswordTokens, userID)
	return err
}

const deleteUserRecoveryCodes = `-- name: DeleteUserRecoveryCodes :exec
DELETE FROM two_factor_recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteUserRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRecoveryCodes, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password, role, is_sso_only,
	two_factor_secret, two_factor_enabled, two_factor_confirmed, deleted_at, created_at, updated_at
FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsSsoOnly,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.TwoFactorConfirmed,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, role, is_sso_only,
	two_factor_secret, two_factor_enabled, two_factor_confirmed, deleted_at, created_at, updated_at
FROM users WHERE lower(email) = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsSsoOnly,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.TwoFactorConfirmed,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (name, email, password, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUserParams struct {
	Name      string
	Email     string
	Password  sql.NullString
	Role      string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listUserNames = `-- name: ListUserNames :many
SELECT id, name, deleted_at FROM users
`

type ListUserNamesRow struct {
	ID        int64
	Name      string
	DeletedAt sql.NullString
}

func (q *Queries) ListUserNames(ctx context.Context) ([]ListUserNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNamesRow{}
	for rows.Next() {
		var i ListUserNamesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, role, is_sso_only,
	two_factor_secret, two_factor_enabled, two_factor_confirmed, deleted_at, created_at, updated_at
FROM users WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsSsoOnly,
			&i.TwoFactorSecret,
			&i.TwoFactorEnabled,
			&i.TwoFactorConfirmed,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithTwoFactorSecret = `-- name: ListUsersWithTwoFactorSecret :many
SELECT id, two_factor_secret FROM users
WHERE two_factor_secret IS NOT NULL AND two_factor_secret != ''
`

type ListUsersWithTwoFactorSecretRow struct {
	ID              int64
	TwoFactorSecret sql.NullString
}

func (q *Queries) ListUsersWithTwoFactorSecret(ctx context.Context) ([]ListUsersWithTwoFactorSecretRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithTwoFactorSecret)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithTwoFactorSecretRow{}
	for rows.Next() {
		var i ListUsersWithTwoFactorSecretRow
		if err := rows.Scan(&i.ID, &i.TwoFactorSecret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserSSOOnly = `-- name: MarkUserSSOOnly :exec
UPDATE users SET is_sso_only=1, updated_at=? WHERE id=?
`

type MarkUserSSOOnlyParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) MarkUserSSOOnly(ctx context.Context, arg MarkUserSSOOnlyParams) error {
	_, err := q.db.ExecContext(ctx, markUserSSOOnly, arg.UpdatedAt, arg.ID)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role=?, updated_at=? WHERE id=?
`

type SetUserRoleParams struct {
	Role      string
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setUserRole, arg.Role, arg.UpdatedAt, arg.ID)
	return err
}

const setUserTwoFactor = `-- name: SetUserTwoFactor :exec
UPDATE users SET two_factor_secret=?, two_factor_enabled=?, two_factor_confirmed=?, updated_at=? WHERE id=?
`

type SetUserTwoFactorParams struct {
	TwoFactorSecret    sql.NullString
	TwoFactorEnabled   int64
	TwoFactorConfirmed int64
	UpdatedAt          sql.NullString
	ID                 int64
}

func (q *Queries) SetUserTwoFactor(ctx context.Context, arg SetUserTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, setUserTwoFactor,
		arg.TwoFactorSecret,
		arg.TwoFactorEnabled,
		arg.TwoFactorConfirmed,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const tombstoneUser = `-- name: TombstoneUser :exec
UPDATE users SET name = 'Deleted user', email = 'deleted-' || id || '@invalid', password = NULL,
	is_sso_only = 0, two_factor_secret = NULL, two_factor_enabled = 0, two_factor_confirmed = 0,
	deleted_at = ?1, updated_at = ?1
WHERE id = ?2
`

type TombstoneUserParams struct {
	Now sql.NullString
	ID  int64
}

// A deleted user keeps their row (ids in space databases still resolve) but
// loses everything that identifies them or lets them sign in.
func (q *Queries) TombstoneUser(ctx context.Context, arg TombstoneUserParams) error {
	_, err := q.db.ExecContext(ctx, tombstoneUser, arg.Now, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password  sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name=?, email=?, role=?, updated_at=? WHERE id=?
`

type UpdateUserProfileParams struct {
	Name      string
	Email     string
	Role      string
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserTwoFactorSecret = `-- name: UpdateUserTwoFactorSecret :exec
UPDATE users SET two_factor_secret=?, updated_at=? WHERE id=?
`

type UpdateUserTwoFactorSecretParams struct {
	TwoFactorSecret sql.NullString
	UpdatedAt       sql.NullString
	ID              int64
}

func (q *Queries) UpdateUserTwoFactorSecret(ctx context.Context, arg UpdateUserTwoFactorSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTwoFactorSecret, arg.TwoFactorSecret, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserWithPassword = `-- name: UpdateUserWithPassword :exec
UPDATE users SET name=?, email=?, role=?, password=?, updated_at=? WHERE id=?
`

type UpdateUserWithPasswordParams struct {
	Name      string
	Email     string
	Role      string
	Password  sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWithPassword,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Password,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
