#!/bin/sh
set -e

# $1 is the number of package instances installed after this scriptlet:
# 1 = fresh install, 2 = upgrade.
getent group savvy-go >/dev/null || groupadd --system savvy-go
getent passwd savvy-go >/dev/null || \
    useradd --system --gid savvy-go --home-dir /var/lib/savvy-go \
        --no-create-home --shell /sbin/nologin savvy-go

exit 0
