package db

import (
	"context"
	"database/sql"
	"fmt"
	"path/filepath"
)

// backup_meta holds key/value metadata inside a backup file. It is not part
// of the Go schema (the live database never has it), so these queries are
// hand-written instead of generated by sqlc.

// OpenReadOnly opens a SQLite file read-only, without the live-database pragmas.
func OpenReadOnly(path string) (*sql.DB, error) {
	return sql.Open("sqlite", "file:"+filepath.ToSlash(path)+"?mode=ro")
}

// ReadBackupMeta returns the backup_meta rows of a backup file; empty when the
// file has no such table or cannot be opened.
func ReadBackupMeta(ctx context.Context, path string) map[string]string {
	out := map[string]string{}
	src, err := OpenReadOnly(path)
	if err != nil {
		return out
	}
	defer src.Close()
	rows, err := src.QueryContext(ctx, `SELECT key, value FROM backup_meta`)
	if err != nil {
		return out
	}
	defer rows.Close()
	for rows.Next() {
		var k, v string
		if rows.Scan(&k, &v) == nil {
			out[k] = v
		}
	}
	return out
}

// WriteBackupMeta stores key/value pairs in a backup file. Existing keys are
// replaced only when overwrite is true. journal_mode=DELETE keeps the backup a
// single self-contained file (no -wal/-shm left beside it).
func WriteBackupMeta(ctx context.Context, path string, kv map[string]string, overwrite bool) error {
	dst, err := sql.Open("sqlite", "file:"+filepath.ToSlash(path)+"?_pragma=journal_mode(DELETE)")
	if err != nil {
		return err
	}
	defer dst.Close()
	if _, err := dst.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS backup_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)`); err != nil {
		return fmt.Errorf("backup meta: %w", err)
	}
	conflict := `ON CONFLICT(key) DO NOTHING`
	if overwrite {
		conflict = `ON CONFLICT(key) DO UPDATE SET value = excluded.value`
	}
	for k, v := range kv {
		if _, err := dst.ExecContext(ctx, `INSERT INTO backup_meta (key, value) VALUES (?, ?) `+conflict, k, v); err != nil {
			return fmt.Errorf("backup meta %s: %w", k, err)
		}
	}
	return nil
}

// DropBackupMeta removes backup_meta from a database about to become live.
func DropBackupMeta(ctx context.Context, sqlDB *sql.DB) error {
	_, err := sqlDB.ExecContext(ctx, `DROP TABLE IF EXISTS backup_meta`)
	return err
}
